django_36/book/urls.py
from django.urls import path
from book import views
from rest_framework.routers import SimpleRouter
from book.api import views as api_views

app_name = 'books'

urlpatterns = [
    path('', views.BookListView.as_view(), name='books-list'),
    path('<int:pk>', views.BookDetailView.as_view(), name='books-detail'),
    path('create/', views.BooksCreateView.as_view(), name='books-create')
]

router = SimpleRouter()
router.register('api', api_views.BookModelViewSet)

urlpatterns += router.urls

django_36/django_36/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('books/', include('book.urls', namespace='books')),
    path('purchases/', include('purchase.urls', namespace='purchases'))
]

django_36/purchase/urls.py
from django.urls import path
from purchase import views
from rest_framework.routers import SimpleRouter
from purchase.api import views as api_views

app_name = 'purchases'

urlpatterns = [
    path('', views.PurchaseListView.as_view(), name='purchases-list'),
    path('<int:pk>', views.PurchaseDetailView.as_view(), name='purchases-detail'),
    path('create/', views.PurchaseCreateView.as_view(), name='purchases-create')
]

router = SimpleRouter()
router.register('api', api_views.PurchaseModelViewSet)

urlpatterns += router.urls

django_36/users/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from users import views
from users.api import views as api_views

app_name = 'users'

urlpatterns = [
    path('', views.UsersListView.as_view(), name='users-list'),
    path('<int:pk>', views.UsersDetailView.as_view(), name='users-detail'),
    path('create/', views.UsersCreateView.as_view(), name='users-create')
]

router = SimpleRouter()
router.register('api', api_views.UsersModelViewSet)

urlpatterns += router.urls

django_36/book/models.py
from django.db import models
from django.urls import reverse_lazy


class Books(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    year = models.IntegerField()
    price = models.FloatField()

    def __str__(self):
        return f"{self.id} {self.title}"

    class Meta:
        db_table = 'book'
        verbose_name = 'Book'
        verbose_name_plural = 'Books'
        unique_together = ('title', 'author')

    def get_absolute_url(self):
        return reverse_lazy('books:books-detail', kwargs={'pk': self.pk})

django_36/purchase/models.py
from django.db import models
from django.urls import reverse_lazy

from users.models import Users
from book.models import Books


class Purchases(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    book = models.ForeignKey(Books, on_delete=models.CASCADE, default='')
    date = models.DateField(auto_now=True)

    def __str__(self):
        return f"{self.id} {self.user.first_name} buy {self.book.title}"

    class Meta:
        db_table = 'purchase'
        verbose_name = 'Purchase'
        verbose_name_plural = 'Purchases'
        ordering = ['-date']

    def get_absolute_url(self):
        return reverse_lazy('purchases:purchases-detail', kwargs={'pk': self.pk})

django_36/users/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import AbstractUser
from django.urls import reverse_lazy


class Users(AbstractUser):
    first_name = models.CharField(null=False, max_length=50)
    last_name = models.CharField(null=False, max_length=50)
    age = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.id} {self.first_name} User "

    class Meta:
        db_table = 'user'
        verbose_name = 'Site User'
        verbose_name_plural = 'Site Users'

    def get_absolute_url(self):
        return reverse_lazy('users:users_detail', kwargs={'pk': self.pk})

django_36/book/api/views.py
from rest_framework.viewsets import ModelViewSet
from book.models import Books
from book.api.serializers import BookSerializer
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend


class BookModelViewSet(ModelViewSet):
    queryset = Books.objects.all()
    serializer_class = BookSerializer
    filter_backends = [DjangoFilterBackend, OrderingFilter, SearchFilter]
    filterset_fields = ('id', 'price')
    search_fields = ('id', 'title')
    ordering_fields = ('-id')

django_36/book/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.urls import reverse_lazy

from book.models import Books
from django.views.generic import ListView, DetailView, CreateView


class BookListView(ListView):
    model = Books


class BookDetailView(DetailView):
    model = Books


class BooksCreateView(CreateView):
    model = Books
    template_name = 'book/books_create.html'
    context_object_name = 'books/books_create.html'
    fields = ('title', 'author', 'year', 'price')
    success_url = reverse_lazy('books:books-list')

django_36/purchase/api/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.viewsets import ModelViewSet
from purchase.models import Purchases
from purchase.api.serializers import PurchaseSerializer
from rest_framework.filters import SearchFilter, OrderingFilter


class PurchaseModelViewSet(ModelViewSet):
    queryset = Purchases.objects.all()
    serializer_class = PurchaseSerializer
    filter_backends = [DjangoFilterBackend, OrderingFilter, SearchFilter]
    filterset_fields = ('book', 'user')
    search_fields = ('id', 'user')
    ordering_fields = ('-id')

django_36/purchase/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.urls import reverse_lazy

from purchase.models import Purchases
from django.views.generic import ListView, DetailView, CreateView


class PurchaseListView(ListView):
    model = Purchases


class PurchaseDetailView(DetailView):
    model = Purchases


class PurchaseCreateView(CreateView):
    model = Purchases
    template_name = 'purchase/purchases_create.html'
    context_object_name = 'purchase/purchases_create.html'
    fields = ('user', 'book')
    success_url = reverse_lazy('purchases:purchases-list')

django_36/users/api/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.viewsets import ModelViewSet
from users.models import Users
from users.api.serializers import UsersSerializer
from rest_framework.filters import SearchFilter, OrderingFilter
from users.api.pagination import CustomPagination


class UsersModelViewSet(ModelViewSet):
    queryset = Users.objects.all()
    serializer_class = UsersSerializer
    filter_backends = [DjangoFilterBackend, OrderingFilter, SearchFilter]
    filterset_fields = ('id', 'age')
    search_fields = ('id', 'last_name')
    ordering_fields = ('-id')
    pagination_class = CustomPagination

django_36/users/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from users.models import Users


class UsersListView(ListView):
    model = Users
    template_name = 'users/users_list.html'
    context_object_name = 'users'


class UsersDetailView(DetailView):
    model = Users
    template_name = 'users/users_detail.html'
    context_object_name = 'users'


class UsersCreateView(CreateView):
    model = Users
    template_name = 'users/users_create.html'
    context_object_name = 'users/users_create.html'
    fields = ('first_name', 'last_name', 'age', 'username')
    success_url = reverse_lazy('users:users-list')

django_36/templates/book/books_create.html
<h1>Create Book</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>

django_36/templates/book/books_detail.html
<h1>{{ books.title }}</h1>
<p>Book id- {{ books.id }}. Book author- {{ books.author }}. Published year- {{ books.year }}.
    Price: {{ books.price }}</p>

django_36/templates/book/books_list.html
<h1>Book list</h1>
<ul>
    {% for obj in object_list %}
        <li>Title- {{ obj.title }}. Author - {{ obj.author }}.
            Published year - {{ obj.year }}. Price- {{ obj.price }}</li>
    {% endfor %}
</ul>

<a href="{% url 'books:books-create' %}">Create New Book</a>

django_36/templates/purchase/purchases_create.html
<h1>Create Purchase</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>

django_36/templates/purchase/purchases_detail.html
<h1>{{ purchases.id }}</h1>
<p>{{ purchases.user.first_name }} {{ purchases.user.last_name }} buy {{ purchases.book.title }}
    on {{ purchases.date }}</p>

django_36/templates/purchase/purchases_list.html
<h1>Purchases list</h1>
<ul>
    {% for obj in object_list %}
        <li>{{ obj.date }} {{ obj.user.first_name }} {{ obj.user.last_name }} buy book - {{ obj.book.title }}</li>
    {% endfor %}
</ul>

<a href="{% url 'purchases:purchases-create' %}">Create New Purchase</a>

django_36/templates/users/users_create.html
<h1>Create User</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>

django_36/templates/users/users_detail.html
<h1>{{ users.first_name }}</h1>
<p>User id- {{ users.id }}. User lastname- {{ users.last_name }}. User age: {{ users.age }}</p>

django_36/templates/users/users_list.html
<h1>Users list</h1>
<ul>
    {% for obj in object_list %}
        <li>{{ obj.first_name }} {{ obj.last_name }} {{ obj.age }} age</li>
    {% endfor %}
</ul>

<a href="{% url 'users:users-create' %}">Create New User</a>